
import React, { useState } from 'react';
import { ReviewReport } from '../types';
import { FileText, CheckCircle2, AlertTriangle, Link2, ScanSearch, Microscope, Feather, ShieldAlert, Gavel, ArrowLeft } from 'lucide-react';

interface ReviewReportViewProps {
  report: ReviewReport;
  onClose: () => void;
  onExport?: () => void;
  onUploadNew?: () => void; // Optional if context differs
}

// Agent definitions for UI visualization
const AGENTS_UI = [
  { id: "Citation Scanner", name: "Citation Scanner", role: "Verification Bot", icon: <ScanSearch className="w-5 h-5" />, color: "text-emerald-600", bg: "bg-emerald-100", border: "border-emerald-200" },
  { id: "Dr. Methodos", name: "Dr. Methodos", role: "Methodology", icon: <Microscope className="w-5 h-5" />, color: "text-blue-600", bg: "bg-blue-100", border: "border-blue-200" },
  { id: "The Citation Police", name: "Citation Police", role: "Audit Officer", icon: <Link2 className="w-5 h-5" />, color: "text-orange-600", bg: "bg-orange-100", border: "border-orange-200" },
  { id: "Prof. Clarity", name: "Prof. Clarity", role: "Structure & Style", icon: <Feather className="w-5 h-5" />, color: "text-purple-600", bg: "bg-purple-100", border: "border-purple-200" },
  { id: "Reviewer #2", name: "Reviewer #2", role: "The Critic", icon: <ShieldAlert className="w-5 h-5" />, color: "text-rose-600", bg: "bg-rose-100", border: "border-rose-200" },
  { id: "Editor-in-Chief", name: "Editor-in-Chief", role: "Final Verdict", icon: <Gavel className="w-5 h-5" />, color: "text-slate-800", bg: "bg-slate-200", border: "border-slate-300" },
];

export const ReviewReportView: React.FC<ReviewReportViewProps> = ({ report, onClose, onExport, onUploadNew }) => {
  const [activeTab, setActiveTab] = useState<number>(0);
  
  const citationScore = report.referenceAudit?.healthScore || 0;
  const citationColor = citationScore >= 90 ? 'text-green-600' : citationScore >= 60 ? 'text-amber-600' : 'text-rose-600';

  const getScoreColor = (score: number) => {
    if (score >= 80) return "text-green-600";
    if (score >= 60) return "text-amber-600";
    return "text-rose-600";
  };

  const getVerdictBadge = (verdict: string) => {
      switch(verdict) {
          case 'Accept': return <span className="px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm font-bold border border-green-200">Accept</span>;
          case 'Minor Revision': return <span className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm font-bold border border-blue-200">Minor Revision</span>;
          case 'Major Revision': return <span className="px-3 py-1 bg-amber-100 text-amber-700 rounded-full text-sm font-bold border border-amber-200">Major Revision</span>;
          case 'Reject': return <span className="px-3 py-1 bg-rose-100 text-rose-700 rounded-full text-sm font-bold border border-rose-200">Reject</span>;
          default: return null;
      }
  };

  return (
     <div className="w-full max-w-5xl mx-auto py-8 animate-fade-in pb-24">
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-8">
           <div>
              <button 
                    onClick={onClose}
                    className="flex items-center gap-2 text-slate-400 hover:text-slate-700 transition-colors mb-2"
                >
                    <ArrowLeft className="w-4 h-4" />
                    <span className="font-medium text-sm">Close Report</span>
                </button>
              <h1 className="text-3xl font-bold text-slate-900">Manuscript Evaluation</h1>
              <p className="text-slate-500 text-sm">Generated by ScholarAgent Peer Review Board</p>
           </div>
           <div className="flex gap-3">
              {onUploadNew && (
                  <button onClick={onUploadNew} className="px-4 py-2 bg-white border border-slate-300 rounded-lg text-sm font-medium hover:bg-slate-50">
                      Upload New
                  </button>
              )}
              {onExport && (
                  <button onClick={onExport} className="px-4 py-2 bg-slate-900 text-white rounded-lg text-sm font-medium hover:bg-slate-800 flex items-center gap-2">
                     <FileText className="w-4 h-4" /> Export PDF
                  </button>
              )}
           </div>
        </div>

        {/* Score Cards */}
        <div className="grid md:grid-cols-4 gap-4 mb-10">
           {/* Overall Score */}
           <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col justify-center items-center text-center">
               <div className="relative w-16 h-16 flex items-center justify-center mb-2">
                   <svg className="w-full h-full transform -rotate-90">
                      <circle cx="32" cy="32" r="28" stroke="#f1f5f9" strokeWidth="6" fill="none" />
                      <circle 
                         cx="32" cy="32" r="28" stroke="currentColor" strokeWidth="6" fill="none" 
                         className={getScoreColor(report.overallScore)}
                         strokeDasharray={`${report.overallScore * 1.75} 175`}
                      />
                   </svg>
                   <span className={`absolute text-lg font-bold ${getScoreColor(report.overallScore)}`}>{report.overallScore}</span>
               </div>
               <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wide">Overall Score</h3>
           </div>

            {/* Citation Health */}
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col justify-center items-center text-center relative overflow-hidden">
               {/* Background Graph Pattern */}
               <div className="absolute inset-0 opacity-5 pointer-events-none">
                   <svg className="w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none">
                       <path d="M0 100 L 20 80 L 40 90 L 60 40 L 80 50 L 100 20" fill="none" stroke="currentColor" strokeWidth="2" className={citationColor} />
                   </svg>
               </div>
               <div className={`text-3xl font-black mb-1 ${citationColor}`}>{citationScore}%</div>
               <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wide flex items-center gap-1">
                   <Link2 className="w-3 h-3" /> Citation Health
               </h3>
               <div className="text-[10px] text-slate-400 mt-1">
                   {report.referenceAudit?.verified} Verified / {report.referenceAudit?.total} Total
               </div>
           </div>

           {/* Verdict */}
           <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col justify-center items-center text-center">
               <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-3">Final Verdict</h3>
               <div className="flex items-center gap-2">
                  {getVerdictBadge(report.finalVerdict)}
               </div>
           </div>

           {/* Probability */}
           <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col justify-center items-center text-center">
               <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-3">Acceptance Prob.</h3>
               <div className="text-xl font-bold text-slate-900">
                  {report.acceptanceProbability}
               </div>
           </div>
        </div>

        {/* Detailed Tabs */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-lg overflow-hidden">
            <div className="flex border-b border-slate-200 overflow-x-auto scrollbar-hide">
                {report.agentReviews.map((agent, idx) => {
                    const uiAgent = AGENTS_UI.find(a => a.name === agent.agentName);
                    return (
                        <button
                        key={idx}
                        onClick={() => setActiveTab(idx)}
                        className={`
                            px-6 py-4 text-sm font-bold whitespace-nowrap transition-colors flex items-center gap-2
                            ${activeTab === idx ? 'border-b-2 border-indigo-600 text-indigo-600 bg-indigo-50/50' : 'text-slate-500 hover:text-slate-800 hover:bg-slate-50'}
                        `}
                        >
                        {uiAgent?.icon}
                        {agent.agentName}
                        </button>
                    );
                })}
            </div>

            <div className="p-8 animate-fade-in key={activeTab}">
                {/* Active Agent Content */}
                <div className="flex justify-between items-start mb-6">
                    <div>
                       <h2 className="text-xl font-bold text-slate-900 mb-1">{report.agentReviews[activeTab].agentName}</h2>
                       <p className="text-sm text-slate-500">{report.agentReviews[activeTab].role}</p>
                    </div>
                    <div className="text-right">
                       <div className="text-2xl font-black text-slate-900">{report.agentReviews[activeTab].score}<span className="text-sm text-slate-400 font-normal">/10</span></div>
                       <div className="text-xs text-slate-400 uppercase font-bold">Agent Score</div>
                    </div>
                </div>

                <div className="prose prose-slate max-w-none">
                   <div className="bg-slate-50 p-4 rounded-xl border border-slate-100 mb-6 text-slate-700 leading-relaxed italic">
                      "{report.agentReviews[activeTab].summary}"
                   </div>

                   <div className="grid md:grid-cols-2 gap-8">
                       <div>
                          <h3 className="flex items-center gap-2 font-bold text-green-700 mb-3">
                             <CheckCircle2 className="w-5 h-5" /> Key Strengths
                          </h3>
                          <ul className="space-y-2">
                             {report.agentReviews[activeTab].strengths.map((s, i) => (
                                <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
                                   <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-green-400 shrink-0"></span>
                                   {s}
                                </li>
                             ))}
                          </ul>
                       </div>
                       
                       <div>
                          <h3 className="flex items-center gap-2 font-bold text-rose-700 mb-3">
                             <AlertTriangle className="w-5 h-5" /> Weaknesses & Flaws
                          </h3>
                          <ul className="space-y-2">
                             {report.agentReviews[activeTab].weaknesses.map((w, i) => (
                                <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
                                   <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-rose-400 shrink-0"></span>
                                   {w}
                                </li>
                             ))}
                          </ul>
                       </div>
                   </div>
                </div>
            </div>
        </div>
     </div>
  );
};
