
export const IEEE_TEMPLATE = [
  "\\documentclass[letterpaper, 10 pt, conference]{ieeeconf}",
  "",
  "\\IEEEoverridecommandlockouts",
  "\\overrideIEEEmargins",
  "",
  "\\usepackage[utf8]{inputenc}",
  "\\usepackage[T1]{fontenc}",
  "\\usepackage{graphics}",
  "\\usepackage{epsfig}",
  "\\usepackage{mathptmx}",
  "\\usepackage{amsmath}",
  "\\usepackage{amssymb}",
  "\\usepackage{url}",
  "\\usepackage{cite}",
  "",
  "\\title{\\LARGE \\bf",
  "{{TITLE}}",
  "}",
  "",
  "\\author{{{AUTHOR_FNM}} {{AUTHOR_SUR}}$^{1}$%",
  "\\thanks{*{{FUNDING}}}%",
  "\\thanks{$^{1}${{AUTHOR_FNM}} {{AUTHOR_SUR}} is with {{AUTHOR_DEPT}}, {{AUTHOR_AFFIL}}",
  "        {\\tt\\small {{AUTHOR_EMAIL}}}}%",
  "}",
  "",
  "\\begin{document}",
  "",
  "\\maketitle",
  "\\thispagestyle{empty}",
  "\\pagestyle{empty}",
  "",
  "\\begin{abstract}",
  "{{ABSTRACT}}",
  "\\end{abstract}",
  "",
  "{{BODY}}",
  "",
  "\\section*{ACKNOWLEDGMENT}",
  "{{FUNDING}}",
  "",
  "{{BIBLIOGRAPHY}}",
  "",
  "\\end{document}"
].join("\n");
